services:
    mysql:
        image: mysql:8.0
        container_name: coducate-mysql-dev
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
